---
- hosts: local
  vars:
    symfony_project_name: automation
    symfony_filename_date_part: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}{{ansible_date_time.tz}}"
    symfony_project_root: /home/hab/public_html/testhab
    symfony_project_repo: https://github.com/abbeshamza/habtest.git
    ansible_ssh_user: test
    symfony_project_post_folder_creation_tasks:  empty.yml
    symfony_project_pre_cache_warmup_tasks: empty.yml
    symfony_project_post_live_switch_tasks: empty.yml
    symfony_project_pre_live_switch_tasks: empty.yml
    symfony_project_env: prod
    symfony_project_composer_path: /home/hab/public_html/testhab/composer.phar
    symfony_project_cache_command: cache:warmup
    symfony_project_composer_opts: '--optimize-autoloader --no-interaction'
    symfony_project_release:  "{{ symfony_filename_date_part }}"

  roles:
    - servergrove.symfony2

  
  tasks:
    - name: Symfony | Setting up default permissions for cache folders 
      command: "chmod -R 777 {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs"

    - shell: echo "deploy complete !!!"
      register: foo
    - debug: msg="{{ foo.stdout }}"
