- hosts: prod
  vars:
    symfony_project_name: automation
    symfony_filename_date_part: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}{{ansible_date_time.tz}}"
    symfony_project_root: /home/hab/public_html/testhab
    symfony_project_repo: https://github.com/abbeshamza/habtest.git
    symfony_project_branch: master
    ansible_ssh_user: test
    symfony_project_post_folder_creation_tasks:  empty.yml
    symfony_project_pre_cache_warmup_tasks: empty.yml
    symfony_project_post_live_switch_tasks: empty.yml
    symfony_project_pre_live_switch_tasks: empty.yml
    symfony_project_env: prod
    symfony_project_composer_path: /home/hab/public_html/testhab/composer.phar
    symfony_project_cache_command: cache:warmup
    symfony_project_composer_opts: '--optimize-autoloader --no-interaction'
    symfony_project_release:  "{{ symfony_filename_date_part }}"


  roles:
    - servergrove.symfony2

  tasks:
   - name: Set cache folder permissions
     shell: >
       APACHEUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data' | grep -v root | head -1 | cut -d\  -f1` &&
       setfacl -R -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs &&
       setfacl -dR -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs
   - shell: echo "deploy complete !!!"
     register: foo
   - debug: msg="{{ foo.stdout }}"
- hosts: dev
  vars:
    symfony_project_name: automation
    symfony_filename_date_part: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}{{ansible_date_time.tz}}"
    symfony_project_root: /home/hab/public_html/devhab
    symfony_project_repo: https://github.com/abbeshamza/habtest.git
    symfony_project_branch: master
    ansible_ssh_user: test
    symfony_project_post_folder_creation_tasks:  empty.yml
    symfony_project_pre_cache_warmup_tasks: empty.yml
    symfony_project_post_live_switch_tasks: empty.yml
    symfony_project_pre_live_switch_tasks: empty.yml
    symfony_project_parameters_file: parameter_dev.yml
    symfony_project_parameters_file: /home/hab/public_html/devhab/shared/app/config/parameters.yml
    symfony_project_env: dev
    symfony_project_composer_path: /home/hab/public_html/devhab/composer.phar
    symfony_project_cache_command: cache:warmup
    symfony_project_composer_opts: '--optimize-autoloader --no-interaction'
    symfony_project_release:  "{{ symfony_filename_date_part }}"


  roles:
    - servergrove.symfony2

  tasks:
   - name: Set cache folder permissions
     shell: >
       APACHEUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data' | grep -v root | head -1 | cut -d\  -f1` &&
       setfacl -R -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs &&
       setfacl -dR -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs
   - shell: echo "deploy complete !!!"
   - copy: src= parameter_dev.yml dest= parameters.yml
   
      
        
