---
- hosts: local
 
  roles:
    - servergrove.symfony2

  tasks:
   - name: Set cache folder permissions
     shell: >
       APACHEUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data' | grep -v root | head -1 | cut -d\  -f1` &&
       setfacl -R -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs &&
       setfacl -dR -m u:"$APACHEUSER":rwX -m u:`whoami`:rwX {{ symfony_project_root }}/current/app/cache {{ symfony_project_root }}/current/app/logs

   - shell: echo "deploy complete !!!"
     register: foo
   - debug: msg="{{ foo.stdout }}"

