- tasks:
    - name: Copy ansible inventory file to client
      copy: src=src='home/hab/public_html/devhab/shared/app/config/parameters.yml' dest'/home/hab/public_html/devhab/current/app/config/parameters.yml'
              owner=root group=root mode=0644
